---
- name: Set ownership
  file: path=/etc/nginx state=directory owner=www-data group=www-data recurse=yes

- name: Create directories
  file: path=/etc/nginx/{{ item }} state=directory owner=www-data group=www-data
  with_items:
    - sites-available
    - sites-enabled