---
- name: Install php5-fpm and associated packages
  apt: name={{ item }} state=latest
  with_items:
    - php5-fpm
    - php5-mcrypt
    - php5-gd
    - php5-mysql
    - php-apc
    - php5-curl
    - php-pear
  notify: restart nginx

- name: fix cgi path in php5-fpm
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
    - restart php5-fpm
    - restart nginx

- name: Set max post size
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)post_max_size =' line='post_max_size = 40M'
  notify:
    - restart php5-fpm
    - restart nginx

- name: Set max upload file size
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)upload_max_filesize =' line='upload_max_filesize = 20M'
  notify:
    - restart php5-fpm
    - restart nginx

- name: enable php5-mcrypt
  shell: php5enmod mcrypt
  args:
    creates: /etc/php5/cli/conf.d/20-mcrypt.ini
  notify:
    - restart php5-fpm
    - restart nginx