---
- name: Push new resolvconf head file
  template: src=head.j2 dest=/etc/resolvconf/resolv.conf.d/head

- name: Push new resolvconf base file
  copy: src=base dest=/etc/resolvconf/resolv.conf.d/base
  notify: bounce resolvconf

- name: Push new hosts
  template: src=hosts.j2 dest=/etc/hosts
  notify: reboot

- name: Push new hostname
  template: src=hostname.j2 dest=/etc/hostname
  notify: reboot

