---
- name: Push new resolvconf head file
  template: src=head.j2 dest=/etc/resolvconf/resolv.conf.d/head

- name: Push new resolvconf base file
  copy: src=base dest=/etc/resolvconf/resolv.conf.d/base
  notify: bounce resolvconf

